module.exports = {
  'promise/always-return': 'error',
  'promise/avoid-new': 'warn',
  'promise/catch-or-return': 'error',
  'promise/no-callback-in-promise': 'warn',
  'promise/no-native': 'off',
  'promise/no-nesting': 'warn',
  'promise/no-new-statics': 'error',
  'promise/no-promise-in-callback': 'warn',
  'promise/no-return-in-finally': 'warn',
  'promise/no-return-wrap': 'error',
  'promise/param-names': 'error',
  'promise/prefer-await-to-callbacks': 'warn',
  'promise/prefer-await-to-then': 'warn',
  'promise/valid-params': 'warn',
};
